/**
 * Centralized UI strings. Provides a single source of truth for all user-facing text.
 * When i18n is needed, this file becomes the default locale and a translation layer is added on top.
 */
export const strings = {
  app: {
    name: "Ghosty",
  },
  nav: {
    home: "Home",
    modes: "Modes",
    dictionary: "Dictionary",
    settings: "Settings",
    help: "Help",
  },
  home: {
    welcomeBack: "Welcome back",
    noActivity: "No activity yet",
    clearHistory: "Clear history",
    copyToClipboard: "Copy to clipboard",
    showThoughts: "Show thoughts",
    hideThoughts: "Hide thoughts",
    showMore: "Show more",
    showLess: "Show less",
    thoughts: "Thoughts",
    today: "Today",
    setupApiKey: "Set up an API key",
    toEnableTranscription: "to enable transcription.",
    holdTooltip: (shortcut: string) =>
      `Hold ${shortcut} to dictate and let Ghosty format for you`,
    heroDescription:
      "Ghosty transforms your vague voice input into optimized AI requests.",
    words: "words",
    statusReady: "Ready.",
    statusRecording: "Recording...",
    statusTranscribing: "Transcribing...",
  },
  modes: {
    title: "Modes",
    description: "Each mode defines how Ghosty transforms your voice into text.",
    newMode: "New mode",
    import: "Import",
    builtIn: "Built-in",
    custom: "Custom",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    duplicate: "Duplicate",
    export: "Export",
    modeNamePlaceholder: "Mode name",
    shortDescriptionPlaceholder: "Short description",
    selectOrCreate: "Select a mode to view its prompt, or create your own.",
    builtInList: "4 built-in modes: Direct, Shape, Reframe, Build.",
    directModeTooltip: "No AI rewrite — just clean transcription.",
    builtInTooltip: "Built-in mode",
    visibleInWidget: "Visible in widget — click to hide",
    hiddenFromWidget: "Hidden from widget — click to show",
    hideFromWidget: "Hide from widget",
    showInWidget: "Show in widget",
    dragToReorder: "Drag to reorder",
    modeActions: "Mode actions",
    duplicateMode: "Duplicate",
    confirmDeletion: "Confirm",
    color: "Color",
    actions: "Actions",
    playground: {
      title: "Playground",
      placeholder: "Type something to test this mode...",
      apply: "Run",
      copy: "Copy",
    },
    importModal: {
      title: "Import modes",
      description:
        "Paste exported JSON. Each mode needs a",
      nameField: "name",
      systemPromptField: "systemPrompt",
    },
  },
  dictionary: {
    title: "Dictionary",
    description:
      "Add acronyms, technical terms, or names to help Ghosty's transcription engine.",
    addWord: "Add word",
    addFirstWord: "Add your first word",
    noDictionaryEntries: "No dictionary entries yet",
    removeEntry: "Remove this entry",
    addVariants: "Add variants",
    variantsPlaceholder: "Variants (a, b, c)",
    guide: {
      title: "How to add words or terms",
      step1:
        'Click <strong class="text-foreground">Add word</strong> to add a word or a correction (recognized form \u2192 preferred form).',
      step2:
        'Optional: on an entry, click <strong class="text-foreground">Add variants</strong> for other spellings.',
      step3:
        "Dictate a sentence containing that word (using your shortcut) and check the result in the Home history.",
      whisperNote:
        "Entries are sent to Whisper as context to guide recognition. If a word is still not recognized well, add variants or a phonetic pronunciation if supported.",
    },
  },
  settings: {
    title: "SETTINGS",
    subtitle: "Preferences",
    closeSettings: "Close settings",
    groups: {
      general: "GENERAL",
      setup: "SETUP",
      configuration: "CONFIGURATION",
      account: "ACCOUNT",
      advanced: "ADVANCED",
    },
    general: {
      title: "General",
      description: "App preferences and profile",
      launchAtLogin: "Launch at login",
      launchAtLoginDesc: "Open Ghosty automatically when you log in",
      autoUpdate: "Auto-update",
      autoUpdateDesc: "Automatically download and install updates",
      version: "Version",
      versionDesc: "App version",
      updates: "Check for updates",
      appUpToDate: "App is up to date",
      versionAvailable: (v: string) => `v${v} available`,
      installUpdate: "Install update",
      installing: "Installing\u2026",
      restartToApply: "Restart to apply",
      checkForUpdates: "Check for updates",
      checking: "Checking\u2026",
      profile: "Profile",
      displayName: "Display name",
      displayNamePlaceholder: "Your name",
      displayNameHint: "Used in the welcome message.",
      save: "Save",
    },
    account: {
      title: "Account",
      description: "Profile and account settings",
      displayName: "Display name",
      displayNamePlaceholder: "Your name",
      displayNameHint: "Used in the welcome message and profile.",
      save: "Save",
    },
    system: {
      title: "System",
      description: "Behavior and macOS integration",
      behavior: "Behavior",
      autoCopy: "Auto-copy to clipboard",
      autoCopyDesc: "Result is automatically copied after dictation",
      soundOnComplete: "Play completion sound",
      soundOnCompleteDesc: "Play a short sound when your dictation is ready",
      systemNotifications: "System notifications",
      systemNotificationsDesc:
        "Show a notification when dictation or transformation is ready",
      autoPaste: "Auto-paste after transform",
      autoPasteDesc:
        "Automatically paste the result when using context menu Services",
      pasteInputAndOutput: "Include original when pasting",
      pasteInputAndOutputDesc:
        "Paste both your original words and the transformed result (format: Original / Result)",
      services: {
        title: "Context menu shortcuts",
        label: "Text mode (context menu)",
        description:
          "Add Ghosty modes to the macOS context menu. One action installs from your current modes.",
        noServices: "No shortcuts installed.",
        upToDate: (count: number) =>
          `Up to date (${count} shortcut${count > 1 ? "s" : ""}).`,
        updateAvailable:
          "Update available (reinstall to sync with current modes).",
        installServices: "Install shortcuts",
        updateServices: "Update shortcuts",
        reinstall: "Reinstall",
        enableModesFirst: "Enable at least one mode first",
        openServicesFolder: "Open Services folder",
        devWarning:
          'Dev only: run Ghosty from the built app (.app), not in dev. Otherwise you may see "No application knows how to open URL ghosty://".',
      },
    },
    shortcuts: {
      title: "Keyboard shortcuts",
      description: "Customize how you interact with Ghosty",
      uniqueNote: "Shortcuts must be unique and not reserved by macOS.",
      validationRules: "Validation rules",
      validationTooltip:
        "No duplicate in this app. Shortcut must be free (e.g. Option+Shift+Space is reserved; Fn cannot be used).",
      listening: "Listening\u2026",
      pressKeys: "Press keys\u2026",
      enabled: "Enabled",
      enableShortcut: "Enable shortcut",
      resetToDefault: "Reset to default",
      resetConfirm: "This will reset all shortcuts to their defaults. Continue?",
      dismiss: "Dismiss",
      errors: {
        fnKey:
          "The Fn key cannot be used for global shortcuts on this system.",
        alreadyUsed: "This shortcut is already used by another action.",
        reserved:
          "Shortcut reserved by macOS or another app. Try Ctrl+Shift+Space or another combination.",
        saveFailed: "Failed to save.",
      },
    },
    recording: {
      title: "Recording",
      description: "Microphone and recording settings",
      inputDevice: "Microphone",
      inputDeviceDefault: "Default",
      inputDeviceHint:
        "Uses your system's default microphone unless you select another.",
      maxDuration: "Max duration (minutes)",
    },
    models: {
      title: "Models",
      description: "Choose your transcription and text generation services",
      transcription: "Voice to text",
      transcriptionDesc: "Service that converts your voice into text",
      provider: "Service",
      providerOpenAI: "OpenAI Whisper",
      providerGroq: "Groq (faster, lower cost)",
      providerGroqDesc: "Uses specialized hardware for near-instant transcription. Requires a Groq API key.",
      providerOpenAIDesc: "Standard OpenAI Whisper API.",
      defaultLanguage: "Language",
      languageHint: "Language for voice recognition. Auto-detect if not set.",
      model: "Model",
      textGeneration: "Text transformation",
      textGenerationDesc: "Service that rewrites your dictation using your chosen mode",
      llmProviderOpenAI: "OpenAI (best quality)",
      llmProviderGroq: "Groq (faster, lower cost)",
      llmProviderGroqDesc: "Open-source models optimized for speed and cost. Requires a Groq API key.",
      llmProviderOpenAIDesc: "OpenAI GPT models. Best quality for complex transformations.",
    },
    apiKeys: {
      title: "API Keys",
      description: "Add your API keys to enable transcription and text generation",
      noKeysYet: "No API keys yet. Add one to get started.",
      setActiveKey: "Set as active key",
      removeKey: "Remove this key",
      name: "Name",
      namePlaceholder: "e.g. My OpenAI key",
      keyPlaceholder: "Paste your API key",
      addApiKey: "Add API key",
      add: "Add",
      providerOpenAI: "OpenAI",
      providerGroq: "Groq",
      providerCustom: "Custom (OpenAI-compatible)",
      storedLocally: "Keys are stored locally in your system keychain.",
    },
  },
  onboarding: {
    welcome: {
      title: "Welcome to Ghosty",
      description:
        "Transform your voice into sharper, better-structured prompts \u2014 instantly, without leaving any app.",
      getStarted: "Get started",
    },
    howItWorks: {
      title: "How it works",
      subtitle: "Three steps, zero friction.",
      step1Label: "Hold shortcut",
      step1Desc:
        "Press the hotkey anywhere to start recording your voice.",
      step2Label: "AI transforms",
      step2Desc:
        "Ghosty transcribes and sharpens your words using your chosen mode.",
      step3Label: "Paste instantly",
      step3Desc:
        "The improved text is copied and pasted into your active window.",
      continue: "Continue",
    },
    apiKey: {
      title: "Connect your API key",
      description:
        "Ghosty uses your OpenAI API key directly \u2014 no account, no subscription beyond what you use.",
      placeholder: "sk-...",
      hideKey: "Hide key",
      showKey: "Show key",
      getApiKey: "Get your API key on platform.openai.com",
      validating: "Validating\u2026",
      testingKey: "Testing key\u2026",
      saving: "Saving\u2026",
      keySaved: "Key saved",
      saveAndContinue: "Save and continue",
      skipForNow: "Skip for now \u2014 I'll add it in Settings",
      errors: {
        enterKey: "Enter your API key.",
        mustStartWithSk: "Key must start with sk-",
      },
    },
    ready: {
      title: "You're all set",
      description:
        "anywhere to start recording. You can change this shortcut in Settings.",
      openGhosty: "Open Ghosty",
    },
  },
  notifications: {
    title: "Notifications",
    noNotifications: "No notifications yet",
    notificationsHint:
      "You'll see tips, milestones, and new feature announcements here.",
    addToDictionary: (word: string) => `Add "${word}" to dictionary`,
    add: "Add",
    dismiss: "Dismiss",
  },
  floatingBar: {
    configureApiKey: "Configure API key",
    copied: "Copied \u00B7 \u2318V",
    loading: "Loading\u2026",
  },
  errors: {
    somethingWentWrong: "Something went wrong",
    appEncounteredProblem:
      "The application encountered a problem. Reload the page to continue.",
    reload: "Reload",
    playgroundError: (e: string) => `Error: ${e}`,
    apiKeyEmpty: "API key cannot be empty",
    openaiKeyPrefix: "OpenAI key must start with 'sk-' or 'sk-proj-'",
    openaiKeyTooShort: "OpenAI key too short: minimum 40 characters",
    invalidCharacters: "Invalid characters detected",
    customKeyTooShort: "Key too short: minimum 10 characters",
    unknownProvider: "Unknown provider",
    deleteApiKeyConfirm: "Are you sure you want to delete this API key?",
    resetUsageConfirm: "Reset usage statistics?",
  },
  addWordModal: {
    title: "Add to vocabulary",
    close: "Close",
    correctMisspelling: "Correct a misspelling",
    correctMisspellingTooltip:
      "When on, define a form that is often misrecognized and the correct form to use.",
    misspelling: "Misspelling",
    misspellingPlaceholder: "e.g. Whispr",
    correctSpelling: "Correct spelling",
    correctSpellingPlaceholder: "e.g. Wispr",
    word: "Word *",
    wordPlaceholder: "Add a new word",
    wordHint: "The word to add to the transcription dictionary",
    adding: "Adding...",
    addWord: "Add word",
    cancel: "Cancel",
    errors: {
      misspellingRequired: "Misspelling and correct spelling are required",
      wordEmpty: "Word cannot be empty",
    },
  },
  profile: {
    guest: "Guest",
    connectAccount: "Connect your account",
    wordsGenerated: (count: number) =>
      count >= 1000
        ? `${(count / 1000).toFixed(1)}K words generated`
        : `${count} words generated`,
    manageAccount: "Manage account",
  },
  voiceButton: {
    recording: "Recording\u2026",
    processing: "Processing\u2026",
    ready: "Voice input ready",
    failed: "Voice input failed",
    start: "Start voice input",
  },
  systemPromptEditor: {
    improvePrompt: "Improve prompt",
    undo: "Undo",
  },
  conversation: {
    noMessages: "No messages yet",
    startConversation: "Start a conversation to see messages here",
  },
  correction: {
    addToDictionary: (word: string) => `Add "${word}" to dictionary`,
    dismiss: "Dismiss",
  },
} as const;
